######## Config ########
workdir: config['workdir']

shell.executable('/bin/bash')
shell.prefix('set +eu; ')


rule all:
    input:
        # qc
        'qc/fastp/fastp.stats.xls',
        'qc/multiqc',
        'qc/demux/demultiplex-summary-forward.png',
        'qc/demux/demultiplex-summary-reverse.png',
        'qc/demux/quality-forward.png',
        'qc/demux/quality-reverse.png',
        # feature
        'feature/demux.qza',
        'feature/demux.qzv',
        'feature/demux_v',
        'feature/dada2/stats',
        'feature/dada2/rep-seqs/dna-sequences.fasta',
        'feature/dada2/table/feature-table.tsv',
        'feature/dada2/table_freq/feature-table.tsv',
        'feature/rarefied_table/feature-table.tsv',
        'feature/rarefied_table_freq/feature-table.tsv',
        'feature/phylogeny/rooted-tree.rectangular.png',
        'feature/phylogeny/rooted-tree.rectangular.pdf',
        'feature/phylogeny/rooted-tree.circular.png',
        'feature/phylogeny/rooted-tree.circular.pdf',
        'feature/phylogeny/unrooted-tree',
        'feature/phylogeny/masked-aligned-rep-seqs',
        'feature/phylogeny/aligned-rep-seqs',
        # taxa
        'taxa/taxonomy.qzv',
        'taxa/taxonomy',
        'taxa/taxonomy_v',
        'taxa/taxonomy_barplot.qzv',
        'taxa/taxonomy_barplot_v',
        expand('taxa/barplot/{levels}',levels=['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']),
        expand('taxa/collapse/{levels}/feature-table.tsv',levels=['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']),
        expand('taxa/collapse_freq/{levels}/feature-table.tsv',levels=['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']),
        expand('taxa/heatmap_hclust2/{levels}.hclust2.txt',levels=['Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']),
        expand('taxa/heatmap_hclust2/{levels}.hclust2.png',levels=['Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']),
        expand('taxa/graphlan/{levels}.graphlan.png',levels=['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species']),
        expand('taxa/krona/{sample}.krona.Species.txt',sample=config['samples']),
        expand('taxa/krona/{sample}.krona.Species.html',sample=config['samples']),
        expand('taxa/krona/{sample}.krona.Species.pdf',sample=config['samples']),
        expand('taxa/krona/{sample}.krona.Species.png',sample=config['samples']),
        # diversity
        'diversity/alpha-rarefaction.qzv',
        'diversity/alpha-rarefaction',
        expand('diversity/alpha/pmetric.{p_metric}.qza', p_metric=['ace', 'chao1', 'simpson', 'shannon', 'goods_coverage', 'observed_features']),
        expand('diversity/alpha/pmetric.{p_metric}', p_metric=['ace', 'chao1', 'simpson', 'shannon', 'goods_coverage', 'observed_features']),
        'diversity/alpha_diversity_stats.tsv',
        expand('diversity/beta/pmetric.{p_metric}.qza',p_metric=['braycurtis', 'jaccard', 'euclidean']),
        expand('diversity/beta/pmetric.{p_metric}',p_metric=['braycurtis', 'jaccard', 'euclidean']),
        'diversity/alpha_rare_curve',
        'diversity/alpha_specaccum/specaccum.png',
        'diversity/alpha_specaccum/specaccum.pdf',
        'diversity/alpha_rank_abundance_curve',
        'diversity/beta_PCOA',
        'diversity/beta_NMDS',
        'diversity/beta_UPGMA',
        'diversity/beta_heatmap',
        'diversity/beta_Adonis',
        # diff
        'diff/Venn/otu',
        'diff/PCA/otu',
        'diff/PLS-DA/otu',
        'diff/OPLS-DA/otu',
        'diff/PLS-DA/Species',
        'diff/OPLS-DA/Species',
        expand('diff/Venn/{levels}',levels=['Family', 'Genus', 'Species']),
        expand('diff/PCA/{levels}',levels=['Family', 'Genus', 'Species']),
        'diff/RandomForest',
        'diff/Lefse',
        # function
        'function/picrust2_plot',
        'function/picrust2_out'

        # FIXME 很多图片结果需要指定输出


include: 'rules/qc_fastqc.smk'
include: 'rules/qc_multiqc.smk'
include: 'rules/qc_fastp.smk'
include: 'rules/feature_fq_import.smk'
include: 'rules/feature_dada2.smk'
include: 'rules/feature_phylogeny.smk'
include: 'rules/diversity_core_metrics.smk'
include: 'rules/taxa.smk'
include: 'rules/diversity_alpha_rarefaction.smk'
include: 'rules/diversity_alpha.smk'
include: 'rules/diversity_beta.smk'
include: 'rules/diversity_plots.smk'
include: 'rules/diff_plot.smk'
include: 'rules/picrust.smk'
